// <auto-generated />
using System;
using BitsAndBobs.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BitsAndBobs.Migrations
{
    [DbContext(typeof(BaB_DbContext))]
    partial class BaB_DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("BitsAndBobs.Models.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustFirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustLastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustPassword")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustUsername")
                        .HasColumnType("TEXT");

                    b.HasKey("CustomerID");

                    b.ToTable("CustomersDB");
                });

            modelBuilder.Entity("BitsAndBobs.Models.Inventory", b =>
                {
                    b.Property<int>("InventoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("InventoryLocationLocationID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("InventoryProductProductID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantityAvailable")
                        .HasColumnType("INTEGER");

                    b.HasKey("InventoryID");

                    b.HasIndex("InventoryLocationLocationID");

                    b.HasIndex("InventoryProductProductID");

                    b.ToTable("InventoryDB");
                });

            modelBuilder.Entity("BitsAndBobs.Models.Location", b =>
                {
                    b.Property<int>("LocationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocationAddress")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LocationCountryID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LocationStateID")
                        .HasColumnType("INTEGER");

                    b.HasKey("LocationID");

                    b.HasIndex("LocationCountryID");

                    b.HasIndex("LocationStateID");

                    b.ToTable("LocationsDB");
                });

            modelBuilder.Entity("BitsAndBobs.Models.LocationCountry", b =>
                {
                    b.Property<int>("LocationCountryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.HasKey("LocationCountryID");

                    b.ToTable("LocationCountry");
                });

            modelBuilder.Entity("BitsAndBobs.Models.LocationState", b =>
                {
                    b.Property<int>("LocationStateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.HasKey("LocationStateID");

                    b.ToTable("LocationState");
                });

            modelBuilder.Entity("BitsAndBobs.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OrderCustomerCustomerID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OrderLocationLocationID")
                        .HasColumnType("INTEGER");

                    b.HasKey("OrderID");

                    b.HasIndex("OrderCustomerCustomerID");

                    b.HasIndex("OrderLocationLocationID");

                    b.ToTable("OrdersDB");
                });

            modelBuilder.Entity("BitsAndBobs.Models.OrderLineItem", b =>
                {
                    b.Property<int>("OrderLineItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LineItemOrderOrderID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LineItemProductProductID")
                        .HasColumnType("INTEGER");

                    b.Property<double>("LinePrice")
                        .HasColumnType("REAL");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("OrderLineItemID");

                    b.HasIndex("LineItemOrderOrderID");

                    b.HasIndex("LineItemProductProductID");

                    b.ToTable("OrderLineItemsDB");
                });

            modelBuilder.Entity("BitsAndBobs.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductName")
                        .HasColumnType("TEXT");

                    b.Property<double>("ProductPrice")
                        .HasColumnType("REAL");

                    b.HasKey("ProductID");

                    b.ToTable("ProductsDB");
                });

            modelBuilder.Entity("BitsAndBobs.Models.Inventory", b =>
                {
                    b.HasOne("BitsAndBobs.Models.Location", "InventoryLocation")
                        .WithMany()
                        .HasForeignKey("InventoryLocationLocationID");

                    b.HasOne("BitsAndBobs.Models.Product", "InventoryProduct")
                        .WithMany()
                        .HasForeignKey("InventoryProductProductID");
                });

            modelBuilder.Entity("BitsAndBobs.Models.Location", b =>
                {
                    b.HasOne("BitsAndBobs.Models.LocationCountry", "LocationCountry")
                        .WithMany()
                        .HasForeignKey("LocationCountryID");

                    b.HasOne("BitsAndBobs.Models.LocationState", "LocationState")
                        .WithMany()
                        .HasForeignKey("LocationStateID");
                });

            modelBuilder.Entity("BitsAndBobs.Models.Order", b =>
                {
                    b.HasOne("BitsAndBobs.Models.Customer", "OrderCustomer")
                        .WithMany()
                        .HasForeignKey("OrderCustomerCustomerID");

                    b.HasOne("BitsAndBobs.Models.Location", "OrderLocation")
                        .WithMany()
                        .HasForeignKey("OrderLocationLocationID");
                });

            modelBuilder.Entity("BitsAndBobs.Models.OrderLineItem", b =>
                {
                    b.HasOne("BitsAndBobs.Models.Order", "LineItemOrder")
                        .WithMany()
                        .HasForeignKey("LineItemOrderOrderID");

                    b.HasOne("BitsAndBobs.Models.Product", "LineItemProduct")
                        .WithMany()
                        .HasForeignKey("LineItemProductProductID");
                });
#pragma warning restore 612, 618
        }
    }
}
