// <auto-generated />
using BitsAndBobs.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BitsAndBobs.Migrations
{
    [DbContext(typeof(BaB_DbContext))]
    partial class BaB_DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");
#pragma warning restore 612, 618
        }
    }
}
